export const UPDATE_FORM = 'UPDATE_FORM';
export const ADD_CHOICE = 'ADD_CHOICE';
export const UPDATE_CHOICE = 'UPDATE_CHOICE';
export const REMOVE_CHOICE = 'REMOVE_CHOICE';
export const SUBMIT_FORM = 'SUBMIT_FORM';
export const SUBMIT_FORM_SUCCESS = 'SUBMIT_FORM_SUCCESS';
export const SUBMIT_FORM_FAILURE = 'SUBMIT_FORM_FAILURE';


export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const GET_STATS = 'GET_STATS';
export const GET_STATS_SUCCESS = 'GET_STATS_SUCCESS';
export const GET_STATS_FAILURE = 'GET_STATS_FAILURE';
export const NEXT_STAT = 'NEXT_STAT';
export const PREVIOUS_STAT = 'PREVIOUS_STAT';
